"""
Django settings for dev2210 project.
Generated by 'django-admin startproject' using Django 4.0.2.
For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from datetime import timedelta

import environ

from .settings_db import *

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f=qq$pq_6wtc-*bum3vb06^karyzmu(xt_#s&_)a3fcfds0p*u"

# Take environment variables from .env file
environ.Env.read_env(Path.joinpath(BASE_DIR, ".env"))

# False if not in os.environ because of casting above
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
SITE_DOMAIN = env("SITE_DOMAIN")
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS")
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS")

# Application definition

INSTALLED_APPS = [
    "dal",
    "dal_select2",
    "admin_menu",
    "grappelli",
    # default entries
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # packages
    "mptt",
    "crispy_forms",
    "crispy_bootstrap5",
    "import_export",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "django_extensions",
    # Apps
    "ebos2201",
    "ebos2202",
    "ebos2206",
    "ebos2210",
    "ebos2215",
    # 'ebos2240',
]

# should not replace all HTML5 input types
GRAPPELLI_CLEAN_INPUT_TYPES = False
IMPORT_EXPORT_USE_TRANSACTIONS = True
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ebos2201.middleware.Ebos2201Middleware",
]

ROOT_URLCONF = "dev2210.urls"
DATABASE_ROUTERS = ["ebos2201.router.Ebos2201Router"]

TEMPLATE_DIR = Path.joinpath(BASE_DIR, "templates")
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            TEMPLATE_DIR,
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dev2210.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Authentication
AUTHENTICATION_BACKENDS = [
    "ebos2201.backends.email_backend.UsernameOrEmailAuthBackend",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "ebos2201.pagination.CustomPageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
}

# Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Ebos22 API",
    "DESCRIPTION": "ERP",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    # 'ENUM_NAME_OVERRIDES': {
    #     # choices is an attribute of class CurrencyContainer containing a list of tuples
    #     'CflControlEnum': 'ebos2201.models.m01_fin_mas.T01Cfl10.CFLCTL_CHOICE',
    #     'CoaSlCatEnum': 'ebos2201.models.m01_core_mas.T01Voc10.COASLCAT_CHOICE',
    #     'ModeOfPayEnum': 'ebos2210.models.m10_fin_link.T10Gld10.MDP_CHOICE',
    #     'VocStatusEnum': 'ebos2210.models.m10_fin_link.T10Gld10.GLDSTATUS_CHOICE',
    #     'ChqStatusEnum': 'ebos2210.models.m10_fin_link.T10Gld11.CHQSTATUS_CHOICE',
    #     'MonthEnum': 'ebos2210.models.m10_fin_gl.T10Glr02.MONTH_CHOICE',
    # }
}

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

USE_L10N = False

DATE_INPUT_FORMATS = ["%d/%m/%Y"]
DATETIME_INPUT_FORMATS = [
    "%Y-%m-%d %H:%M:%S",  # '2006-10-25 14:30:59'
    "%Y-%m-%d %H:%M:%S.%f",  # '2006-10-25 14:30:59.000200'
    "%Y-%m-%d %H:%M",  # '2006-10-25 14:30'
    "%Y-%m-%d",  # '2006-10-25'
    "%m/%d/%Y %H:%M:%S",  # '10/25/2006 14:30:59'
    "%m/%d/%Y %H:%M:%S.%f",  # '10/25/2006 14:30:59.000200'
    "%m/%d/%Y %H:%M",  # '10/25/2006 14:30'
    "%m/%d/%Y",  # '10/25/2006'
    "%m/%d/%y %H:%M:%S",  # '10/25/06 14:30:59'
    "%m/%d/%y %H:%M:%S.%f",  # '10/25/06 14:30:59.000200'
    "%m/%d/%y %H:%M",  # '10/25/06 14:30'
    "%m/%d/%y",  # '10/25/06'
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_DIR = Path.joinpath(BASE_DIR, "static")
STATIC_URL = "/static/"

if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / "static",
        "/",
    ]
else:
    STATIC_ROOT = Path.joinpath(BASE_DIR, "static")

# Media Files -  User Uploaded files
MEDIA_DIR = Path.joinpath(BASE_DIR, "documents")
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = "/documents/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django admin customization
ADMIN_LOGO = "logo.png"
ADMIN_STYLE = {
    "primary-color": "#2B3746",
    "secondary-color": "#354151",
    "tertiary-color": "#F2F9FC",
    "logo-width": "auto",
    "logo-height": "35px",
}

MENU_WEIGHT = {"Auth": 100}

# Grappelli Title
GRAPPELLI_ADMIN_TITLE = "ebos22 powered by Aiems"

# Email configuration
EMAIL_HOST = "smtp.gmail.com"  # mail service smtp
EMAIL_PORT = 587
EMAIL_USE_TLS = True

AUTH_USER_MODEL = "ebos2201.User"
LOGOUT_REDIRECT_URL = "/"

# Payment Gateway
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")
STRIPE_ENDPOINT_SECRET = env("STRIPE_ENDPOINT_SECRET")
